[phases.setup]
nixPkgs = ['python39', 'chromium']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['playwright install chromium']

[start]
cmd = 'python run_signals.py'
